name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

template: |
  ## [$RESOLVED_VERSION] - $DATE
  
  $CHANGES

categories:
  - title: '### Added'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '### Changed'
    labels:
      - 'change'
      - 'update'
      - 'refactor'
  - title: '### Deprecated'
    labels:
      - 'deprecated'
  - title: '### Removed'
    labels:
      - 'removal'
  - title: '### Fixed'
    labels:
      - 'bug'
      - 'fix'
  - title: '### Security'
    labels:
      - 'security'

change-template: '- $TITLE (#$NUMBER)'
change-title-escapes: '\<*_&'

exclude-labels:
  - 'skip-changelog'
  - 'documentation'
  - 'chore'

# Automatische labeling op basis van PR titel
autolabeler:
  - label: 'feature'
    title:
      - '/^feat/i'
      - '/^feature/i'
      - '/^add/i'
  
  - label: 'enhancement'
    title:
      - '/^enhance/i'
      - '/^improve/i'
  
  - label: 'bug'
    title:
      - '/^fix/i'
      - '/^bug/i'
      - '/^bugfix/i'
  
  - label: 'fix'
    title:
      - '/^patch/i'
      - '/^hotfix/i'
  
  - label: 'change'
    title:
      - '/^change/i'
      - '/^modify/i'
  
  - label: 'update'
    title:
      - '/^update/i'
      - '/^upgrade/i'
      - '/^bump/i'
  
  - label: 'refactor'
    title:
      - '/^refactor/i'
  
  - label: 'security'
    title:
      - '/security/i'
      - '/\bCVE\b/'
  
  - label: 'deprecated'
    title:
      - '/deprecat/i'
  
  - label: 'removal'
    title:
      - '/^remove/i'
      - '/^delete/i'
  
  - label: 'documentation'
    title:
      - '/^docs/i'
      - '/^doc/i'
      - '/documentation/i'
  
  - label: 'chore'
    title:
      - '/^chore/i'

version-resolver:
  major:
    labels:
      - 'breaking-change'
  minor:
    labels:
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'bug'
      - 'fix'
      - 'security'
      - 'update'
  default: patch
