# Generated by Django 5.1.7 on 2025-03-12 12:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeidentificationJob',
            fields=[
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_file', models.FileField(upload_to='uploads')),
                ('output_file', models.FileField(blank=True, null=True, upload_to='results')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('patient_column', models.CharField(default='patient', max_length=100)),
                ('time_column', models.CharField(default='time', max_length=100)),
                ('caretaker_column', models.CharField(default='caretaker', max_length=100)),
                ('report_column', models.CharField(default='report', max_length=100)),
            ],
        ),
    ]
