# Generated by Django 5.2.5 on 2025-09-15 14:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeidentificationJob',
            fields=[
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_cols', models.CharField(max_length=500)),
                ('input_file', models.FileField(upload_to='input')),
                ('output_file', models.FileField(blank=True, null=True, upload_to='output')),
                ('key_file', models.FileField(blank=True, null=True, upload_to='input')),
                ('log_file', models.FileField(blank=True, null=True, upload_to='output')),
                ('zip_file', models.FileField(blank=True, null=True, upload_to='output')),
                ('zip_preview', models.JSONField(blank=True, null=True)),
                ('processed_preview', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
        ),
    ]
