# Generated by Django 5.2.8 on 2025-11-18 19:28

import api.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeidentificationJob',
            fields=[
                ('job_id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('input_cols', models.CharField(blank=True)),
                ('input_file', models.FileField(upload_to=api.models.input_path)),
                ('datakey', models.FileField(blank=True, null=True, upload_to=api.models.input_path)),
                ('output_file', models.FileField(blank=True, null=True, upload_to=api.models.output_path)),
                ('log_file', models.FileField(blank=True, null=True, upload_to=api.models.output_path)),
                ('zip_file', models.FileField(blank=True, null=True, upload_to=api.models.output_path)),
                ('zip_preview', models.JSONField(blank=True, null=True)),
                ('preview', models.JSONField(blank=True, null=True)),
                ('processed_preview', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
        ),
    ]
