# Generated by Django 5.2.6 on 2025-10-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeidentificationJob',
            fields=[
                ('job_id', models.CharField(editable=False, max_length=250, primary_key=True, serialize=False)),
                ('input_cols', models.CharField()),
                ('input_file', models.FileField(upload_to='input')),
                ('datakey', models.FileField(blank=True, null=True, upload_to='input')),
                ('output_file', models.FileField(blank=True, null=True, upload_to='output')),
                ('log_file', models.FileField(blank=True, null=True, upload_to='output')),
                ('zip_file', models.FileField(blank=True, null=True, upload_to='output')),
                ('zip_preview', models.JSONField(blank=True, null=True)),
                ('processed_preview', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
        ),
    ]
